language: go
go: 1.12.x

install:
  - go mod download


jobs:
  include:
      - name: "hw_1"
        env: DIR=hw_1
      - name: "hw_2"
        env: DIR=hw_2
      - name: "hw_3"
        env: DIR=hw_3
      - name: "hw_4"
        env: DIR=hw_4
      - name: "hw_5"
        env: DIR=hw_5
      - name: "hw_6"
        env: DIR=hw_6
      - name: "hw_7"
        env: DIR=hw_7
      - name: "hw_8"
        env: DIR=hw_8

script:
  - go build $DIR/*.go
  - go vet ./$DIR/...
  - golint -set_exit_status $DIR/...
  - cd $DIR
  - go test ./...
