language: go
go: 1.12.x

install:
  - go get github.com/beevik/ntp
  - go get golang.org/x/lint/golint
  - go get github.com/stretchr/testify

jobs:
  include:
      - name: "hw_1"
        env: DIR=hw_1
      - name: "hw_2"
        env: DIR=hw_2
      - name: "hw_3"
        env: DIR=hw_3
      - name: "hw_4"
        env: DIR=hw_4
      - name: "hw_5"
        env: DIR=hw_5

script:
  - go build $DIR/*.go
  - go vet $DIR/*.go
  - golint -set_exit_status $DIR/*.go
  - cd $DIR
  - go test
