language: go
go: 1.12.x

install:
  - go mod init github.com/vmikhaylov/otus-go/hw-1
  - go get github.com/beevik/ntp
  - go get golang.org/x/lint/golint

script:
  - go build hw_1/main.go
  - go vet hw_1/main.go
  - golint hw_1/main.go
