language: go
go: 1.12.x

install:
  - go get github.com/beevik/ntp
  - go get golang.org/x/lint/golint
  - go get github.com/stretchr/testify

jobs:
  include:
      - name: "hw_1"
        env: DIR=hw_1
      - name: "hw_2"
        env: DIR=hw_1

script:
  - go build $DIR/*.go
  - go vet $DIR/*.go
  - golint $DIR/*.go
  - go test $DIR
